name: Django App Tests

on:
  push:
    branches:
      - develop
      - test
      - main
  pull_request:
    branches:
      - develop
      - test
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install psycopg

      - name: Set DJANGO_SECRET_KEY for tests
        run: echo "DJANGO_SECRET_KEY=test-secret-key-123" >> $GITHUB_ENV

      - name: Run Migrations
        env:
          DJANGO_ENV: test
          DATABASE_NAME: test_db
          DATABASE_USER: test_user
          USER_PASSWORD: testpassword
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        env:
          DJANGO_ENV: test
          DATABASE_NAME: test_db
          DATABASE_USER: test_user
          USER_PASSWORD: testpassword
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          GITHUB_ACTIONS: true
        run: python manage.py test --keepdb

      - name: Update TEST_RESULTS Markdown file
        run: python update_test_results.py

      - name: Commit and Push TEST_RESULTS file to branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          TARGET_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Target branch is: $TARGET_BRANCH"

          git add TEST_RESULTS.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update test results in markdown"
            git push https://${{ secrets.GH_TOKEN }}@github.com/Dhanrajshyam/LittleLemon.git HEAD:$TARGET_BRANCH
          fi

      - name: Update README Markdown file
        run: |
          python update_readme.py

      - name: Commit and Push README file to branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Extract branch name dynamically
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TARGET_BRANCH="${{ github.base_ref }}"
          else
            TARGET_BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update readme in markdown"
            git push https://${{ secrets.GH_TOKEN }}@github.com/Dhanrajshyam/LittleLemon.git HEAD:$TARGET_BRANCH
          fi
